# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: Validate Bicep Template

variables:
  vmImageName: 'windows-latest'

  azureServiceConnection: 'service-jagslab'
  resourceGroupName: 'rg-sql-test-neu-03'
  location: 'northeurope'
  templateFile: './main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
# - task: RunARMTTKTests@1
#   inputs:
#     templatelocation: '$(System.DefaultWorkingDirectory)\*'
#     resultLocation: '$(System.DefaultWorkingDirectory)'
#     allTemplatesMain: false
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group validate --resource-group $(resourceGroupName) --template-file $(templateFile)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)\Test Results\*.xml'
  condition: always()
